spring:
  datasource:
#    url: jdbc:postgresql://18.139.219.235:5433/checkin-service
#    username: boeing
#    password: boeing
    url: jdbc:postgresql://localhost:5432/checkin-service
    username: postgres
    password: 12345

    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update

  application:
    name: check-in-service

server:
  port: 8083

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
  default-produces-media-type: application/json