server:
  address: 0.0.0.0
  port: 8080
spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: true
    gateway:
      discovery:
        locator:
          enabled: true
          refresh-rate: 5s
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/users/**

        - id: booking-service
          uri: lb://BOOKING-SERVICE
          predicates:
            - Path=/booking-service/**

        - id: flight-service
          uri: lb://FLIGHT-SERVICE
          predicates:
            - Path=/flight-service/**

        - id: check-in-service
          uri: lb://CHECK-IN-SERVICE
          predicates:
            - Path=/check-in-service/**

        - id: aircraft-service
          uri: lb://AIRCRAFTSERVICE
          predicates:
            - Path=/air-craft/**

        - id: loyalty-service
          uri: lb://LOYALTY-SERVICE
          predicates:
            - Path=/loyalty-service/**

        - id: user-service-swagger
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/swagger-ui.html
          filters:
            - RewritePath=/user-service(?<segment>/?.*), $\{segment}

        - id: check-in-service-swagger
          uri: lb://CHECK-IN-SERVICE
          predicates:
            - Path=/check-in-service/swagger-ui.html
          filters:
            - RewritePath=/check-in-service(?<segment>/?.*), $\{segment}

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, info, routes

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}