server:
  port: 8080
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/users/**

        - id: booking-service
          uri: lb://BOOKING-SERVICE
          predicates:
            - Path=/booking-service/**

        - id: flight-service
          uri: lb://FLIGHT-SERVICE
          predicates:
            - Path=/flight-service/**

        - id: check-in-service
          uri: lb://CHECK-IN-SERVICE
          predicates:
            - Path=/api/v1/checkin/**

        - id: aircraft-service
          uri: lb://AIRCRAFTSERVICE
          predicates:
            - Path=/air-craft/**

        - id: loyalty-service
          uri: lb:http://LOYALTY-SERVICE
          predicates:
            - Path=/loyalty-service/**

        - id: user-service-swagger
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/swagger-ui.html
          filters:
            - RewritePath=/user-service(?<segment>/?.*), $\{segment}

        - id: check-in-service-swagger
          uri: lb://CHECK-IN-SERVICE
          predicates:
            - Path=/check-in-service/swagger-ui.html
          filters:
            - RewritePath=/check-in-service(?<segment>/?.*), $\{segment}


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka