services:
  postgres:
    container_name: boeing-postgres
    image: postgres
    environment:
      POSTGRES_USER: boeing
      POSTGRES_PASSWORD: boeing
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
      - ./db/init-db:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    restart: unless-stopped

  rabbitmq:
    container_name: boeing-rabbitmq
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    restart: unless-stopped
volumes:
  postgres: