package com.boeing.bookingservice.saga;

public enum SagaStep {
    STARTED,
    AWAITING_FARE_AVAILABILITY_RESPONSE,
    FARE_AVAILABILITY_VALIDATED,
    FARE_AVAILABILITY_CHECKED,
    AWAITING_SEAT_AVAILABILITY_RESPONSE,
    SEAT_AVAILABILITY_CHECKED,
    AWAITING_VOUCHER_VALIDATION_RESPONSE,
    VOUCHER_VALIDATED,
    AWAITING_PENDING_BOOKING_CREATION,
    PENDING_BOOKING_CREATED,    
    AWAITING_PAYMENT_IPN,
    PAYMENT_COMPLETED,
    AWAITING_SEAT_CONFIRMATION,
    SEATS_CONFIRMED,
    AWAITING_LS_VOUCHER_USE_RESPONSE,
    VOUCHER_USED,
    AWAITING_LS_POINTS_EARN_RESPONSE,
    POINTS_EARNED,
    AWAITING_NS_NOTIFICATION_RESPONSE,
    COMPLETED_SUCCESSFULLY,
    FAILED_PROCESSING,
    FAILED_FARE_UNAVAILABLE,
    FAILED_SEAT_UNAVAILABLE,
    FAILED_INVALID_VOUCHER,    
    FAILED_PAYMENT,
    FAILED_SEAT_CONFIRMATION,
    FAILED_VOUCHER_USE,
    FAILED_POINTS_EARN,
    FAILED_FETCH_FLIGHT_DETAILS,
    FAILED_VNPAY_URL_GENERATION,
    CANCELLED_CLIENT_TIMEOUT,
    COMPENSATING_REFUND_PENDING,
    COMPENSATED_REFUND_COMPLETED;    
    public boolean isTerminalState() {
        return this == COMPLETED_SUCCESSFULLY ||
                this == FAILED_FARE_UNAVAILABLE ||
                this == FAILED_SEAT_UNAVAILABLE ||
                this == FAILED_FETCH_FLIGHT_DETAILS ||
                this == FAILED_VNPAY_URL_GENERATION ||
                this == FAILED_PAYMENT ||
                this == FAILED_SEAT_CONFIRMATION ||
                this == FAILED_PROCESSING ||
                this == CANCELLED_CLIENT_TIMEOUT ||
                this == COMPENSATED_REFUND_COMPLETED;
    }
}