server:
  port: 8085

spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: loyalty-service
  cloud:
    config:
      uri: http://localhost:8888
      fail-fast: true
  eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/
    instance:
      prefer-ip-address: true